### PR TITLE
feat: add post process function after documents list fetch

### PR DESCRIPTION
**Pull request by Yelinz**

### CODE REVIEW

**Review by derrabauke — DISMISSED** [review]
LGTM :+1:

**Comment by czosel** [comment]
Assuming this is for the thumbnails - I think we should build the whole implementation into ember-alexandria (also behind a feature flag) to mirror the backend part.

**Comment by Yelinz** [comment]
This is not for thumbnails, this is so apps so that they can for example resolve `created_by_user` if its an id.

**Comment by czosel** [comment]
Ah, sorry for the noise then 🙃

**Comment by czosel** [comment]
if we return the documents in the postprocess function we’d open up the possibility to extend the return value with custom things, similar to the „processNew“ function in ember-caluma. What do you think?

**Comment by Yelinz** [comment]
sure we can do that

**Comment by czosel** [comment]
Nice! Now all this still needs from my side is some mention in the README :-)

**Review by czosel — APPROVED** [review]
:100:

**Pull request merged**
